<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TemplateService.Contracts\TemplateService.Contracts.csproj" />
        <ProjectReference Include="..\TemplateService.Core\TemplateService.Core.csproj" />
        <ProjectReference Include="..\TemplateService.Domain\TemplateService.Domain.csproj" />
        <ProjectReference Include="..\TemplateService.Infrastructure.Postgres\TemplateService.Infrastructure.Postgres.csproj" />
    </ItemGroup>

</Project>