<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="Dapper" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TemplateService.Core\TemplateService.Core.csproj" />
    </ItemGroup>

</Project>