<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\TemplateService.Contracts\TemplateService.Contracts.csproj" />
        <ProjectReference Include="..\TemplateService.Domain\TemplateService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="FluentValidation" />
        <ProjectReference Include="FluentValidation.DependencyInjectionExtensions" />
    </ItemGroup>

</Project>